### ISSUE TITLE
How can I get the UCFKinect dataset?

### ISSUE THREAD

**Issue by shjwjj** [oziris/Gesture-Recognition#1]
I got "403Forbidden You don't have permission to access /~smasood/datasets/UCFKinect.zip on this server."
Do you know how to deal with it?

**Comment by oziris** [comment]
The original authors of the dataset have removed it from the internet or at least the address where it was stored before. Here is another copy:  
https://drive.google.com/open?id=0BzsvT1ThcL7mVE9URWRsclU1UkU

**Comment by shjwjj** [comment]
Successfully get the dataset through your link. Thank you so much for help!

**Comment by oziris** [comment]
You are welcome.
